// ─────────────────────────────────────────────────────────────────────────────
// PLACEHOLDER — do not edit this file during practice.
//
// Create your answer directory and copy a stub into it:
//
//   mkdir -p practice_problem_answers/cw_answer_01_activity_feed
//   cp practice_problems/problem_01_activity_feed.jsx \
//      practice_problem_answers/cw_answer_01_activity_feed/App.jsx
//
// Then run dev or tests pointing at your answer directory:
//
//   PRACTICE_ANSWER=practice_problem_answers/cw_answer_01_activity_feed npm run dev
//   PRACTICE_ANSWER=practice_problem_answers/cw_answer_01_activity_feed npm run test:01
//
// See CLAUDE.md for the full workflow.
// ─────────────────────────────────────────────────────────────────────────────

export default function App() {
  return (
    <div style={{ padding: 24, fontFamily: 'monospace', color: '#475569' }}>
      <h2 style={{ marginBottom: 8 }}>Interview Practice</h2>
      <p style={{ marginBottom: 12 }}>
        Create your answer directory and start the dev server with <code>PRACTICE_ANSWER</code>:
      </p>
      <pre
        style={{
          background: '#f1f5f9',
          padding: '10px 14px',
          borderRadius: 6,
          fontSize: 13,
        }}
      >
        {`mkdir -p practice_problem_answers/cw_answer_01_activity_feed
cp practice_problems/problem_01_activity_feed.jsx \\
   practice_problem_answers/cw_answer_01_activity_feed/App.jsx

PRACTICE_ANSWER=practice_problem_answers/cw_answer_01_activity_feed npm run dev`}
      </pre>
    </div>
  )
}
